import {
    aminBG,
    aryanaBG, 
    baharanBG, 
    erfanBG, 
    fatemehBG, 
    fathimaBG, 
    hamidrezaBG, 
    melikaBG, 
    minaBG, 
    mohammadBG, 
    motaharehBG, 
    pegahBG, 
    reihanehBG, 
    unkown,
    saminBG,
    royanBG,
    gezalBG,
    edwinBG,
    zahraBG,
    event2023Pic1,
    event2023Pic2,
    event2023Pic3,
    event2023Pic4,
    event2023Pic5,
    event2023Pic6,
    event2024,
    heroimage
} from "../../assets";

export const slides = [
  // {
  //   id: "1",
  //   src: heroImage,
  //   title: "Samin Majidi",
  //   description: "Samin Majidi",
  // },
  {
    id: "1",
    src: event2023Pic1,
    title: "TEDxAveLorne 2023",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "2",
    src: event2023Pic2,
    title: "TEDxAveLorne 2023",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "3",
    src: event2023Pic3,
    title: "TEDxAveLorne 2023",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "4",
    src: event2023Pic4,
    title: "TEDxAveLorne 2023",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "5",
    src: event2023Pic5,
    title: "TEDxAveLorne 2023",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "6",
    src: event2023Pic6,
    title: "TEDxAveLorne 2023",
    description: "TEDxAveLorne 2023",
  },

  {
    id: "20",
    src: heroimage,
    title: "TEDxAveLorne 2023",
    description: "TEDxAveLorne 2023",
  },
  // {
  //   id: "30",
  //   src: event2024,
  //   title: "TEDxAveLorne 2024",
  //   description: "TEDxAveLorne 2024",
  // },
  {
    id: "40",
    src: saminBG,
    title: "Samin Majidi",
    description: "Samin Majidi",
  },
  {
    id: "50",
    src: fatemehBG,
    title: "Fatemeh Tavanaei",
    description: "Fatemeh Tavanaei",
  },
  // {
  //   id: "70",
  //   src: Reihaneh,
  //   title: "Reihaneh Ghoroghchian",
  //   description: "Reihaneh Ghoroghchian",
  // },
  {
    id: "60",
    src: erfanBG,
    title: "Mohammaderfan Mohit",
    description: "Mohammaderfan Mohit",
  },

  {
    id: "80",
    src: melikaBG,
    title: "Melika Seyedi",
    description: "Melika Seyedi",
  },
  {
    id: "90",
    src: hamidrezaBG,
    title: "Hamidreza Ermagan",
    description: "Hamidreza Ermagan",
  },
  {
    id: "100",
    src: baharanBG,
    title: "Baharan Nouriinanloo",
    description: "Baharan Nouriinanloo",
  },
  {
    id: "110",
    src: motaharehBG,
    title: "Motahareh Pourrahimi",
    description: "Motahareh Pourrahimi",
  },
  {
    id: "120",
    src: royanBG,
    title: "Royan Jafari",
    description: "Royan Jafari",
  },
  {
    id: "130",
    src: fathimaBG,
    title: "Fathima Nihatha Lathiff",
    description: "Fathima Nihatha Lathiff",
  },
  {
    id: "140",
    src: minaBG,
    title: "Mina Taraghi",
    description: "Mina Taraghi",
  },
  {
    id: "150",
    src: mohammadBG,
    title: "Mohammad Zaid",
    description: "Mohammad Zaid",
  },
  {
    id: "160",
    src: aryanaBG,
    title: "Aryana Haghjoo",
    description: "Aryana Haghjoo",
  },
  {
    id: "170",
    src: pegahBG,
    title: "Pegah Einakchi",
    description: "Pegah Einakchi",
  },
  {
    id: "180",
    src: edwinBG,
    title: "Edwin Meriaux",
    description: "Edwin Meriaux",
  },
  {
    id: "190",
    src: gezalBG,
    title: "Gezal Najafi",
    description: "Gezal Najafi",
  },
  {
    id: "200",
    src: zahraBG,
    title: "Zahra Ahmadi",
    description: "Zahra Ahmadi",
  },
  {
    id: "210",
    src: aminBG,
    title: "Mohammad Amin Shamshiri",
    description: "Mohammad Amin Shamshiri",
  },
];
